sudo: false
language:
   - cpp
   - python
python: 3.6
compiler: g++
os: linux

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - python3

install:
    - pip install --user --upgrade pip
    - pip install --user --upgrade pytest
    - pip install --user pexpect
    
script:
    - g++ -o main main.cpp
    - pytest 
