student_file: main.cpp
build:
    build_system: make
    build_file: main.cpp
run:
    student_soln_exe: student
    test_runner_file: runner.py

nose_report_file: nosetests.xml
run_student_file: False
run_nosetests: True

full_scores:
    test_binary_exists:
        full_score: 0
        description: Does the program compile?
    test_output:
        full_score: 4
        description: Outputs correctly?
    test_input_output:
        full_score: 6
        description: Inserts name into output correctly?
  
